### ISSUE TITLE
Indexer not picked up from Prowlarr by Sonarr

### ISSUE THREAD

**Issue by mgdigital** [mgdigital/rarbg-selfhosted#6]
Currently the indexer does not sync from Prowlarr to Sonarr and I can only add it manualy in Sonarr. Syncing from Prowlarr to Radarr works however.

**Comment by KonradStuewe** [comment]
That kind of sounds like a problem with prowlarr/sonarr rather than with this repo.
I don't know if a change you did since creating this issue has fixed this, but it's certainly working for me.

As long as prowlarr can access and search the torznab api, there should be no reason why it's not syncing it to sonarr.
Maybe it's a configuration problem with prowlarr?
